origin_backupでは、もともとT.origというファイルを使用していたが、
なぜかpython側から呼び出すときにTが生成されないので、最初からTにかえた